### ISSUE TITLE
quiet=True still prints number of cores used and available during blast

### ISSUE THREAD

**Issue by vmkalbskopf** [jsgounot/PyBlast#1]
I have set `quiet = True`for my blast, but ` ncore : 8 - available : 8` is still printing to screen.
Am I missing something? This shouldn't happen, right? I presume it's a subprocess printing, and has not been suppressed.

**Comment by vmkalbskopf** [comment]
I commented out this line in `utils.py` 
```print ("ncore : %i - available : %i" %(ncore, cpu_count()))```
Good enough.

**Comment by jsgounot** [comment]
Hi! Wow, I wasn't expecting anyone to use this library, thank you for trying this out!
I've updated the library to be fully quiet, hope this help.
